export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const NO_ACTION = 'NO_ACTION';
export const SET_USER = 'SET_USER';
export const SET_I18N_LOCALE = 'SET_I18N_LOCALE';
export const SET_I18N_COMP_TERMS = 'SET_I18N_COMP_TERMS';
